name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  packer-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Packer
        uses: hashicorp/setup-packer@v2

      - name: Build AMI with Packer
        run: |
          cd packer
          packer init .
          packer build golden-ami.pkr.hcl

  terraform-deploy:
    runs-on: ubuntu-latest
    needs: packer-build
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Terraform Init & Apply
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
        run: |
          cd terraform
          terraform init
          terraform apply -auto-approve

  ansible-configure:
    runs-on: ubuntu-latest
    needs: terraform-deploy
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install Ansible
        run: pip install ansible boto3 botocore

      - name: Generate Dynamic Inventory
        run: |
          cd ansible
          python3 scripts/generate_inventory.py

      - name: Run Playbook
        run: |
          cd ansible
          ansible-playbook -i inventory.yaml playbook.yml

