name: Deploy Infra + Config

on:
  push:
    branches: [ "main" ]

jobs:
  infra:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.6.6

      - name: Init & Apply Terraform
        run: |
          terraform init
          terraform apply -auto-approve

  config:
    runs-on: ubuntu-latest
    needs: infra
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install deps
        run: pip install boto3 ansible pyyaml

      - name: Generate AWS Inventory
        run: python ansible/aws_inventory.py

      - name: Run Ansible
        run: ansible-playbook -i aws_inventory.yml ansible/site.yml
